#!/usr/bin/env bash
set -euo pipefail

export JAVA_HOME=/tmp/r1-jdk17
export ANDROID_HOME=/tmp/r1-android-sdk
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export PATH="$JAVA_HOME/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
export SAM_BUILD_PYTHON="${SAM_BUILD_PYTHON:-/tmp/sam-python/cpython-3.13.2-linux-x86_64-gnu/bin/python3.13}"
ANDROID_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT_ROOT="$(cd "$ANDROID_ROOT/.." && pwd)"

if [[ ! -x "$SAM_BUILD_PYTHON" ]]; then
    echo "Python 3.13 build host not found: $SAM_BUILD_PYTHON" >&2
    echo "Set SAM_BUILD_PYTHON to an executable Python 3.13 path." >&2
    exit 1
fi

# Keep host-generated bytecode out of the Android package. These directories
# contain only disposable Python caches; source and installed dependencies stay
# untouched. This also makes repeated builds reproducible after local tests.
find "$PROJECT_ROOT/runtime" -type d -name __pycache__ -prune -exec rm -rf -- {} +
PIP_STAGE="$ANDROID_ROOT/runtime-host/build/python/pip/debug/common"
if [[ -d "$PIP_STAGE" ]]; then
    find "$PIP_STAGE" -type d -name __pycache__ -prune -exec rm -rf -- {} +
fi

WEB_ASSETS="$ANDROID_ROOT/runtime-host/src/main/assets"
mkdir -p "$WEB_ASSETS/design" "$WEB_ASSETS/management"
cp "$ANDROID_ROOT/../web/design/tokens.css" "$WEB_ASSETS/design/tokens.css"
cp "$ANDROID_ROOT/../web/design/base.css" "$WEB_ASSETS/design/base.css"
cp "$ANDROID_ROOT/../web/management/index.html" "$WEB_ASSETS/management/index.html"
cp "$ANDROID_ROOT/../web/management/management.css" "$WEB_ASSETS/management/management.css"
cp "$ANDROID_ROOT/../web/management/app.js" "$WEB_ASSETS/management/app.js"
cp "$ANDROID_ROOT/../web/management/build07.js" "$WEB_ASSETS/management/build07.js"
cp "$ANDROID_ROOT/../web/management/background-agent.js" "$WEB_ASSETS/management/background-agent.js"
cp "$ANDROID_ROOT/../web/management/t3.js" "$WEB_ASSETS/management/t3.js"
cp "$ANDROID_ROOT/../web/management/heptabase.js" "$WEB_ASSETS/management/heptabase.js"
cd "$ANDROID_ROOT"

/tmp/gradle-9.5.0/bin/gradle --no-daemon --no-configuration-cache testDebugUnitTest :app:assembleDebug
"$ANDROID_ROOT/scripts/check_boundaries.sh"
"$ANDROID_ROOT/scripts/check_runtime_package.sh"
