package com.resonolabs.ui.design;

/**
 * Geometry of the packed Pixel head atlases. GENERATED by core/design/art/pack_pixel_head.py;
 * do not edit by hand. Buckets are ordered smallest first; poses 0..24 run through the head's
 * sway from one extreme (0) through the centre pose (12) to the other (24). All coordinates are
 * bucket pixels.
 */
final class PixelHeadAtlas {
    private PixelHeadAtlas() {}

    static final int POSES = 25;
    static final int COLUMNS = 5;
    static final int GUTTER = 2;
    /** Nominal square frame size each bucket was rendered at. */
    static final int[] FRAME = {72, 112, 176, 256};
    static final int[] CELL_W = {66, 106, 164, 238};
    static final int[] CELL_H = {64, 106, 162, 234};
    /** The head's centre (middle of its swing extents) inside a cell. */
    static final float[] ANCHOR_X = {33.00f, 53.00f, 82.00f, 119.00f};
    static final float[] ANCHOR_Y = {32.00f, 53.00f, 81.00f, 117.00f};
    /** Height of the head art (top of the band / wings to the hair ends), the size the app scales to. */
    static final float[] HEAD_H = {60.00f, 102.00f, 158.00f, 230.00f};
    static final int[] ACTIVE_W = {61, 97, 150, 216};
    static final int[] ACTIVE_H = {23, 35, 52, 73};
    static final int[] ACTIVE_SLOT_W = {65, 101, 154, 220};
    static final int[] ACTIVE_SLOT_H = {27, 39, 56, 77};
    static final int[] BLINK_W = {30, 46, 70, 99};
    static final int[] BLINK_H = {17, 25, 36, 50};
    static final int[] BLINK_SLOT_W = {34, 50, 74, 103};
    static final int[] BLINK_SLOT_H = {21, 29, 40, 54};
    /** Top of the blink patch grid inside the patch atlas (active patches start at 0). */
    static final int[] BLINK_TOP = {135, 195, 280, 385};
    /** Per pose: where each patch goes inside the idle cell. */
    static final int[][] ACTIVE_X = {
            {3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3},
            {4, 4, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7},
            {8, 8, 8, 8, 8, 8, 9, 10, 11, 11, 12, 12, 12, 12, 12, 12, 11, 12, 12, 11, 12, 10, 11, 10, 10},
            {12, 12, 12, 13, 14, 13, 14, 15, 16, 18, 18, 20, 20, 18, 18, 18, 18, 18, 17, 17, 17, 16, 16, 16, 16}};
    static final int[][] ACTIVE_Y = {
            {25, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22},
            {42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38},
            {66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 65, 66, 66, 60, 59, 59, 59, 58, 58, 58, 58, 58, 59, 59, 59},
            {96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 87, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86}};
    static final int[][] BLINK_X = {
            {5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 8, 8, 8, 8, 9, 9, 10, 10, 10, 10, 11, 11, 12, 12, 12},
            {8, 8, 8, 8, 9, 10, 10, 10, 11, 12, 12, 13, 14, 14, 15, 15, 16, 16, 18, 18, 18, 18, 19, 19, 19},
            {13, 12, 13, 13, 14, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 26, 26, 27, 28, 28, 29, 30, 30, 30},
            {20, 20, 21, 21, 22, 22, 24, 24, 26, 27, 28, 30, 32, 33, 35, 36, 38, 39, 40, 42, 42, 43, 44, 44, 44}};
    static final int[][] BLINK_Y = {
            {25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26},
            {42, 42, 42, 43, 43, 43, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 45, 45, 45, 45, 45, 45, 45},
            {66, 66, 66, 66, 66, 67, 68, 68, 68, 68, 68, 68, 68, 69, 69, 69, 70, 70, 70, 70, 70, 70, 70, 70, 70},
            {97, 97, 97, 98, 98, 98, 98, 98, 98, 98, 99, 100, 100, 100, 100, 100, 101, 101, 102, 102, 102, 102, 102, 102, 102}};
    static final int[] TALK_W = {9, 11, 14, 18};
    static final int[] TALK_H = {8, 10, 13, 17};
    static final int[] TALK_SLOT_W = {13, 15, 18, 22};
    static final int[] TALK_SLOT_H = {12, 14, 17, 21};
    /** Top of the talk (mouth open) patch grid inside the patch atlas, below the blink grid. */
    static final int[] TALK_TOP = {240, 340, 480, 655};
    static final int[][] TALK_X = {
            {14, 14, 14, 14, 15, 15, 16, 16, 16, 16, 16, 18, 18, 18, 18, 18, 20, 20, 20, 20, 20, 20, 21, 21, 21},
            {24, 24, 24, 24, 24, 25, 26, 26, 26, 27, 28, 28, 29, 30, 30, 32, 32, 32, 33, 34, 34, 34, 35, 35, 35},
            {38, 38, 38, 38, 39, 40, 40, 41, 42, 42, 44, 44, 46, 48, 48, 50, 50, 52, 52, 53, 54, 54, 55, 55, 55},
            {56, 56, 56, 56, 58, 58, 60, 60, 62, 63, 64, 66, 68, 70, 72, 72, 74, 76, 77, 78, 79, 80, 81, 81, 81}};
    static final int[][] TALK_Y = {
            {42, 42, 42, 42, 42, 42, 43, 43, 43, 43, 43, 43, 43, 43, 43, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44},
            {72, 72, 72, 72, 72, 72, 72, 73, 73, 73, 73, 73, 73, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74},
            {112, 112, 112, 112, 113, 113, 113, 113, 113, 114, 114, 114, 114, 114, 115, 115, 115, 115, 116, 116, 116, 116, 116, 116, 116},
            {163, 164, 164, 164, 164, 164, 164, 164, 165, 165, 166, 166, 166, 166, 167, 168, 168, 168, 168, 168, 168, 168, 168, 168, 168}};
}
