package com.resonolabs.ui.design;

/**
 * Geometry of the packed Pixel head atlases. GENERATED by core/design/art/pack_pixel_head.py;
 * do not edit by hand. Buckets are ordered smallest first; poses run from yaw -28 (0) through
 * front (12) to +28 degrees (24). All coordinates are bucket pixels.
 */
final class PixelHeadAtlas {
    private PixelHeadAtlas() {}

    static final int POSES = 25;
    static final int COLUMNS = 5;
    static final int GUTTER = 2;
    /** Nominal square frame size each bucket was rendered at. */
    static final int[] FRAME = {72, 112, 176, 256};
    static final int[] CELL_W = {66, 108, 168, 240};
    static final int[] CELL_H = {64, 105, 162, 234};
    /** The head's centre (middle of its swing extents) inside a cell. */
    static final float[] ANCHOR_X = {33.00f, 54.00f, 84.00f, 120.00f};
    static final float[] ANCHOR_Y = {32.00f, 53.00f, 81.00f, 117.00f};
    /** Wing tip to neck height of the head, the size the app scales to. */
    static final float[] HEAD_H = {60.00f, 101.00f, 158.00f, 230.00f};
    static final int[] ACTIVE_W = {27, 40, 60, 86};
    static final int[] ACTIVE_H = {17, 24, 36, 50};
    static final int[] ACTIVE_SLOT_W = {31, 44, 64, 90};
    static final int[] ACTIVE_SLOT_H = {21, 28, 40, 54};
    static final int[] BLINK_W = {20, 31, 46, 64};
    static final int[] BLINK_H = {10, 12, 16, 21};
    static final int[] BLINK_SLOT_W = {24, 35, 50, 68};
    static final int[] BLINK_SLOT_H = {14, 16, 20, 25};
    /** Top of the blink patch grid inside the eyes atlas (active patches start at 0). */
    static final int[] BLINK_TOP = {105, 140, 200, 270};
    /** Per pose: where the eye patch goes inside the idle cell. */
    static final int[][] ACTIVE_X = {
            {11, 12, 12, 12, 12, 12, 14, 14, 15, 16, 18, 18, 20, 20, 22, 23, 24, 24, 26, 26, 26, 28, 28, 28, 28},
            {20, 20, 20, 21, 22, 22, 24, 25, 27, 28, 30, 32, 34, 36, 38, 40, 41, 43, 44, 46, 46, 47, 48, 48, 48},
            {32, 32, 33, 34, 34, 36, 38, 40, 43, 45, 48, 51, 54, 57, 60, 63, 65, 68, 70, 72, 74, 74, 75, 76, 76},
            {45, 45, 46, 48, 49, 51, 54, 57, 60, 64, 68, 73, 77, 81, 86, 90, 94, 97, 100, 103, 105, 106, 108, 109, 109}};
    static final int[][] ACTIVE_Y = {
            {34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34},
            {58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 59, 59, 59, 59, 59, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58},
            {90, 90, 90, 90, 90, 90, 90, 91, 91, 91, 92, 92, 91, 92, 92, 91, 91, 91, 90, 90, 90, 90, 90, 90, 90},
            {131, 131, 132, 132, 132, 132, 132, 132, 132, 132, 133, 133, 133, 133, 133, 132, 132, 132, 132, 132, 132, 132, 132, 131, 131}};
    static final int[][] BLINK_X = {
            {15, 15, 15, 16, 16, 16, 18, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 28, 30, 30, 30, 31, 31, 31},
            {25, 25, 26, 26, 26, 28, 29, 30, 32, 34, 35, 36, 38, 40, 42, 44, 46, 47, 48, 50, 50, 52, 52, 52, 52},
            {40, 40, 40, 42, 42, 44, 46, 48, 50, 52, 56, 58, 61, 64, 66, 70, 72, 74, 76, 78, 80, 80, 82, 82, 82},
            {57, 58, 58, 60, 61, 64, 66, 68, 72, 76, 80, 84, 88, 92, 96, 100, 104, 108, 110, 112, 115, 116, 118, 118, 119}};
    static final int[][] BLINK_Y = {
            {37, 37, 37, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 37, 37, 37},
            {64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 65, 64, 65, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64},
            {99, 99, 99, 100, 100, 100, 100, 100, 100, 100, 100, 100, 101, 100, 100, 100, 100, 100, 100, 100, 100, 100, 99, 99, 99},
            {145, 145, 145, 145, 145, 146, 146, 146, 146, 146, 147, 146, 147, 146, 147, 146, 146, 146, 146, 146, 145, 145, 145, 145, 145}};
}
