(function(){
const checking=document.querySelector("#checking"),pairing=document.querySelector("#pairing"),workspace=document.querySelector("#workspace");let csrf="",polling=false;
async function api(path,options={}){const headers={Accept:"application/json",...(options.headers||{})};if(csrf&&options.method&&options.method!=="GET")headers["X-CSRF-Token"]=csrf;const response=await fetch(path,{credentials:"same-origin",...options,headers});const body=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(body.error?.message||body.message||"This setting could not be saved.");error.status=response.status;throw error}return body}
function show(target){checking.hidden=target!==checking;pairing.hidden=target!==pairing;workspace.hidden=target!==workspace}
function setState(id,text,tone=""){const el=document.querySelector(id);el.className="state "+tone;el.querySelector("span").textContent=text}
async function boot(){try{const body=await api("/v1/management/status");renderStatus(body)}catch(error){if(error.status===401||error.status===403){show(pairing);setState("#shell-state","Pairing required")}else{show(checking);checking.querySelector(".support").textContent=error.message;setState("#shell-state","Offline","error")}}}
function renderStatus(body){show(workspace);csrf=body.csrfToken||csrf;window.__samCsrfToken=csrf;const ready=body.status==="ready";setState("#runtime-state",ready?"Ready":"Needs attention",ready?"ready":"error");setState("#shell-state",ready?"R1 ready":"Needs attention",ready?"ready":"error");document.querySelector("#service").textContent=body.service||"Unavailable";document.querySelector("#contract").textContent=body.contractVersion??"—";document.querySelector("#migration").textContent=body.database?.migrationVersion??"—";loadProfile();loadOpenAI();loadSubscription();loadMemory()}
document.querySelector("#pair-form").addEventListener("submit",async e=>{e.preventDefault();const message=document.querySelector("#pair-error");message.textContent="";try{await api("/v1/management/pair",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:new FormData(e.currentTarget).get("code")})});await boot()}catch(error){message.textContent=error.message}});
async function loadProfile(){try{const body=await api("/v1/management/profile");document.querySelector("#display-name").value=body.displayName||""}catch(error){document.querySelector("#profile-message").textContent=error.message}}
document.querySelector("#profile-form").addEventListener("submit",async e=>{e.preventDefault();const message=document.querySelector("#profile-message");try{await api("/v1/management/profile",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({displayName:new FormData(e.currentTarget).get("displayName")})});message.textContent="Name saved."}catch(error){message.textContent=error.message}});
document.querySelector("#restart").onclick=async()=>{const message=document.querySelector("#status-message");try{await api("/v1/management/restart",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});message.textContent="Runtime restart requested."}catch(error){message.textContent=error.message}};
const labels={"gpt-5.6-sol":"GPT-5.6 Sol","gpt-5.6-terra":"GPT-5.6 Terra","gpt-5.6-luna":"GPT-5.6 Luna","gpt-live-1":"Live","gpt-realtime-2.1":"Realtime 2.1","gpt-realtime-2.1-mini":"Realtime 2.1 Mini"};
function options(select,values,current,empty){select.replaceChildren();if(!values?.length){select.add(new Option(empty,""));return}values.forEach(value=>select.add(new Option(labels[value]||value,value,false,value===current)))}
async function loadOpenAI(){const message=document.querySelector("#openai-message");try{const body=await api("/v1/management/openai"),platform=body.connections?.platform??body.connected,subscription=body.connections?.subscription??false;setState("#openai-state",body.connected?"Configured":"Not configured",body.connected?"ready":"");document.querySelector("#platform-form").hidden=platform;document.querySelector("#platform-disconnect").hidden=!platform;const form=document.querySelector("#model-form");form.hidden=!body.connected;const access=document.querySelector("#access-path");access.replaceChildren();if(platform)access.add(new Option("OpenAI Platform API","platform",false,body.accessPath==="platform"));if(subscription)access.add(new Option("ChatGPT / Codex subscription","subscription",false,body.accessPath==="subscription"));options(document.querySelector("#realtime-model"),body.models?.realtime,body.selection?.realtime,"No Voice model available");options(document.querySelector("#text-model"),body.models?.text,body.selection?.text,"No text model available");document.querySelector("#reasoning-effort").value=body.selection?.reasoning||"none"}catch(error){message.textContent=error.message}}
document.querySelector("#platform-form").addEventListener("submit",async e=>{e.preventDefault();const message=document.querySelector("#openai-message");try{await api("/v1/management/openai/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({apiKey:new FormData(e.currentTarget).get("apiKey")})});e.currentTarget.reset();message.textContent="Platform API connected.";await loadOpenAI()}catch(error){message.textContent=error.message}});
document.querySelector("#platform-disconnect").onclick=async()=>{try{await api("/v1/management/openai/disconnect",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});await loadOpenAI()}catch(error){document.querySelector("#openai-message").textContent=error.message}};
document.querySelector("#model-form").addEventListener("submit",async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));try{await api("/v1/management/openai/access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accessPath:values.accessPath})});await api("/v1/management/openai/models",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});document.querySelector("#openai-message").textContent="Model choices saved.";await loadOpenAI()}catch(error){document.querySelector("#openai-message").textContent=error.message}});
async function loadSubscription(){try{const body=await api("/v1/management/openai/subscription");setState("#subscription-state",body.connected?"Connected":"Not connected",body.connected?"ready":"");document.querySelector("#subscription-connect").hidden=body.connected;document.querySelector("#subscription-disconnect").hidden=!body.connected;if(body.connected){polling=false;document.querySelector("#subscription-auth").hidden=true}}catch(error){document.querySelector("#subscription-message").textContent=error.message}}
let subscriptionAuthSessionId="";
document.querySelector("#subscription-connect").onclick=async()=>{const message=document.querySelector("#subscription-message");try{const body=await api("/v1/management/openai/subscription/start",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});subscriptionAuthSessionId=body.authSessionId||"";document.querySelector("#subscription-code").textContent=body.userCode||body.user_code||"—";document.querySelector("#subscription-link").href=body.verificationUrl||body.verificationUriComplete||body.verification_uri||"https://auth.openai.com/codex/device";document.querySelector("#subscription-auth").hidden=false;polling=Boolean(subscriptionAuthSessionId);if(polling)pollSubscription()}catch(error){message.textContent=error.message}};
async function pollSubscription(){if(!polling||!subscriptionAuthSessionId)return;try{const body=await api("/v1/management/openai/subscription/poll",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({authSessionId:subscriptionAuthSessionId})});if(body.status==="completed"||body.runtime?.connected){polling=false;subscriptionAuthSessionId="";await loadSubscription();await loadOpenAI();return}}catch(error){document.querySelector("#subscription-message").textContent=error.message}setTimeout(pollSubscription,3000)}
document.querySelector("#subscription-disconnect").onclick=async()=>{try{await api("/v1/management/openai/subscription/disconnect",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});await loadSubscription();await loadOpenAI()}catch(error){document.querySelector("#subscription-message").textContent=error.message}};
async function loadMemory(){const target=document.querySelector("#memory-summary");try{const [memory,sessions]=await Promise.all([api("/v1/management/memory"),api("/v1/management/memory/sessions")]);const memories=memory.memories||memory.items||[],reviewed=sessions.sessions||sessions.items||[];target.innerHTML=`<article><small>Saved memories</small><strong>${memories.length}</strong></article><article><small>Reviewed sessions</small><strong>${reviewed.length}</strong></article>`}catch(error){document.querySelector("#memory-message").textContent=error.message}}
document.querySelector("#memory-reindex").onclick=async()=>{const message=document.querySelector("#memory-message");try{await api("/v1/management/memory/reindex",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});message.textContent="Memory search rebuilt."}catch(error){message.textContent=error.message}};
document.querySelectorAll(".nav").forEach(button=>button.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x===button));document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.dataset.panel===button.dataset.page));history.replaceState(null,"",`#${button.dataset.page}`);document.dispatchEvent(new CustomEvent("sam:page",{detail:button.dataset.page}))});
boot();
})();
