(function(){
const panel=document.querySelector("#library-panel"),importDialog=document.querySelector("#import-dialog"),confirmDialog=document.querySelector("#confirm-dialog"),mailDialog=document.querySelector("#mail-dialog"),calendarDialog=document.querySelector("#calendar-dialog");let library="skills",pending=null,confirmJob=null;
const config={
skills:{title:"Import Agent Instructions",help:"Choose one file named exactly SKILLS.MD. Select Voice or Background Agent; importing again replaces that agent’s current document after confirmation.",accept:".MD",documents:true,list:"/v1/management/skills",preflight:"/v1/management/skills/preflight",confirm:"/v1/management/skills/confirm",accent:"#79f2dd",header:"X-SAM-Skill-Filename"},
plugins:{title:"Import a Plugin",help:"Choose a standard Agent Plugin package.",accept:".zip",list:"/v1/management/plugins",preflight:"/v1/management/plugins/preflight",confirm:"/v1/management/plugins/confirm",accent:"#c792ff",header:"X-SAM-Plugin-Filename"},
mcp:{title:"Import MCP tools",help:"Choose a standard mcp.json server definition.",accept:".json",list:"/v1/management/mcp/connections",preflight:"/v1/management/mcp/imports/preflight",confirm:"/v1/management/mcp/imports/confirm",accent:"#c792ff"},
tools:{title:"Tools",list:"/v1/management/tools",accent:"#79f2dd",readOnly:true},
creations:{title:"Import a Creation",help:"Choose a Creation archive or use the details decoded from an official Rabbit QR code.",accept:".zip",list:"/v1/management/creations",preflight:"/v1/management/creations/preflight",confirm:"/v1/management/creations/confirm",accent:"#ffd166",qr:true,header:"X-SAM-Creation-Filename"}
};
async function api(path,options={}){const headers={Accept:"application/json",...(options.headers||{})},csrf=window.__samCsrfToken;if(csrf&&options.method&&options.method!=="GET")headers["X-CSRF-Token"]=csrf;const response=await fetch(path,{credentials:"same-origin",...options,headers});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error?.message||body.message||"This action could not be completed.");return body}
const pick=body=>body.items||body.skills||body.plugins||body.connections||body.tools||body.creations||body.accounts||[];
const name=item=>item.displayName||item.label||item.name||item.title||item.toolName||"Unnamed item";
const id=item=>item.skillId||item.pluginId||item.creationId||item.calendarAccountId||item.accountId||item.connectionId||item.id||item.name;
const plain=value=>String(value||"Available").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const detail=item=>item.description||item.summary||plain(item.sourceType||item.kind||item.healthState||"Configured on this R1");
function base(item){const value=encodeURIComponent(id(item));return library==="mcp"?`/v1/management/mcp/connections/${value}`:`/v1/management/${library}/${value}`}
function row(item,cfg,{actions=true}={}){const lifecycle=item.lifecycleState||item.state;const enabled=item.enabled!==false&&lifecycle!=="disabled"&&lifecycle!=="installed";const el=document.createElement("article");el.className="row";el.innerHTML=`<i class="rail" style="--row-accent:${cfg.accent}"></i><div class="row-copy"><strong></strong><small></small><span class="state ${enabled?"ready":""}"><i></i><span>${plain(lifecycle||item.healthState||(enabled?"available":"disabled"))}</span></span></div><div class="row-actions"></div>`;el.querySelector("strong").textContent=name(item);el.querySelector("small").textContent=detail(item);if(actions&&!cfg.readOnly){const toggle=document.createElement("button");toggle.className="secondary";toggle.textContent=enabled?"Turn off":"Turn on";toggle.onclick=async()=>{try{await api(`${base(item)}/${enabled?"disable":"enable"}`,{method:"POST"});await loadLibrary()}catch(error){show(error.message)}};const remove=document.createElement("button");remove.className="remove";remove.textContent="Delete";remove.onclick=()=>askDelete(item);el.querySelector(".row-actions").append(...(cfg.documents?[remove]:[toggle,remove]))}return el}
async function loadLibrary(){const cfg=config[library];panel.className="loading";panel.textContent=`Loading ${library}…`;try{const list=pick(await api(cfg.list));panel.className="";panel.replaceChildren();const head=document.createElement("div");head.className="section-head";head.innerHTML=`<div><h2>${plain(library)}</h2><p class="support">${list.length} ${list.length===1?"item":"items"} configured</p></div>`;if(!cfg.readOnly){const button=document.createElement("button");button.textContent=cfg.title;button.onclick=openImport;head.append(button)}panel.append(head);const catalog=document.createElement("div");catalog.className=list.length?"catalog":"empty";if(!list.length)catalog.textContent=`No ${library} configured yet.`;else list.forEach(item=>catalog.append(row(item,cfg)));panel.append(catalog)}catch(error){panel.className="notice error";panel.textContent=error.message}}
document.querySelectorAll(".library-nav button").forEach(button=>button.onclick=()=>{library=button.dataset.library;document.querySelectorAll(".library-nav button").forEach(x=>x.classList.toggle("active",x===button));loadLibrary()});
document.addEventListener("sam:page",event=>{if(event.detail==="library")loadLibrary();if(event.detail==="connections"){loadConnections();loadMail();loadCalendars()}});
function openImport(){const cfg=config[library],form=document.querySelector("#import-form");form.reset();pending=null;document.querySelector("#import-title").textContent=cfg.title;document.querySelector("#import-help").textContent=cfg.help;document.querySelector("#import-file").accept=cfg.accept;document.querySelector("#file-field").hidden=false;document.querySelector("#qr-fields").hidden=true;document.querySelector("#import-review").hidden=true;document.querySelector("#import-message").textContent="";document.querySelector("#import-next").textContent="Review import";const kind=document.querySelector("#import-kind");kind.replaceChildren();document.querySelectorAll('input[name="audience"]').forEach(input=>{input.closest("label").hidden=cfg.documents&&input.value==="both";if(cfg.documents&&input.value==="voice")input.checked=true});if(cfg.qr){const button=document.createElement("button");button.type="button";button.className="secondary";button.textContent="Use Rabbit QR details";button.onclick=()=>{document.querySelector("#qr-fields").hidden=false;document.querySelector("#file-field").hidden=true;button.hidden=true};kind.append(button)}importDialog.showModal()}
document.querySelector("#import-form").addEventListener("submit",async event=>{event.preventDefault();const button=document.querySelector("#import-next"),cfg=config[library],audience=new FormData(event.currentTarget).get("audience");button.disabled=true;try{if(pending){await api(cfg.confirm,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({preflightToken:pending.preflightToken,replace:pending.state==="conflict"})});importDialog.close();await loadLibrary();return}let endpoint=cfg.preflight,options;if(cfg.qr&&!document.querySelector("#qr-fields").hidden){endpoint="/v1/management/creations/qr/preflight";options={method:"POST",headers:{"Content-Type":"application/json","X-SAM-Agent-Audience":audience},body:JSON.stringify({title:document.querySelector("#qr-title").value,url:document.querySelector("#qr-url").value,description:document.querySelector("#qr-description").value,themeColor:document.querySelector("#qr-color").value})}}else{const file=document.querySelector("#import-file").files[0];if(!file)throw new Error("Choose a file before continuing.");const headers={"Content-Type":file.type||"application/octet-stream","X-SAM-Agent-Audience":audience,"X-SAM-Filename":file.name};if(cfg.header)headers[cfg.header]=file.name;options={method:"POST",headers,body:file}}pending=await api(endpoint,options);if(pending.state==="blocked"||!pending.preflightToken){const reason=pending.reason||"This package did not pass validation.";pending=null;throw new Error(reason)}const review=document.querySelector("#import-review");review.hidden=false;review.replaceChildren();const title=document.createElement("strong"),copy=document.createElement("span"),route=document.createElement("span");title.textContent=pending.candidate?.displayName||pending.candidate?.name||pending.candidate?.title||pending.displayName||pending.name||pending.title||"Ready to install";copy.textContent=pending.state==="conflict"?"An item with this name already exists. Continuing will replace it.":"Validation passed. Nothing has been installed yet.";route.textContent=`Available to: ${plain(audience)}`;review.append(title,copy,route);button.textContent=pending.state==="conflict"?"Replace existing item":"Install"}catch(error){const message=document.querySelector("#import-message");if(pending&&/preflight is unknown|already used|preflight expired/i.test(error.message)){pending=null;document.querySelector("#import-review").hidden=true;button.textContent="Review import again";message.textContent="The review expired or the runtime restarted. Review this file again before installing."}else message.textContent=error.message}finally{button.disabled=false}});
function askDelete(item){document.querySelector("#confirm-title").textContent=`Delete ${name(item)}?`;document.querySelector("#confirm-copy").textContent="This removes the configured item from this R1. This cannot be undone.";confirmJob=async()=>{await api(base(item),{method:"DELETE"});await loadLibrary();await loadConnections()};confirmDialog.showModal()}
document.querySelector("#confirm-action").onclick=async event=>{event.preventDefault();if(!confirmJob)return;const job=confirmJob;confirmJob=null;confirmDialog.close();try{await job()}catch(error){show(error.message)}};
async function loadConnections(){const target=document.querySelector("#connections-list");target.className="loading";target.textContent="Loading connections…";try{const list=pick(await api("/v1/management/connections")).filter(item=>item.kind!=="mail"&&item.kind!=="calendar");target.className=list.length?"catalog":"empty";target.replaceChildren();if(!list.length){target.textContent="No other connections configured.";return}list.forEach(item=>target.append(row(item,{accent:item.kind==="mcp"?"#c792ff":"#79f2dd",readOnly:true},{actions:false})))}catch(error){target.className="notice error";target.textContent=error.message}}
async function loadMail(){const target=document.querySelector("#mail-list");target.className="loading";target.textContent="Loading mail accounts…";try{const list=pick(await api("/v1/management/mail/accounts"));target.className=list.length?"catalog":"empty";target.replaceChildren();if(!list.length){target.textContent="No mail accounts connected.";return}list.forEach(item=>{const el=row(item,{accent:"#ffd166",readOnly:true},{actions:false}),remove=document.createElement("button");remove.className="remove";remove.textContent="Remove account";remove.onclick=()=>{document.querySelector("#confirm-title").textContent=`Remove ${name(item)}?`;document.querySelector("#confirm-copy").textContent="This removes the account and locally synchronized data from this R1. It does not delete messages from the mail provider.";confirmJob=async()=>{await api(`/v1/management/mail/accounts/${encodeURIComponent(id(item))}`,{method:"DELETE"});await loadMail()};confirmDialog.showModal()};el.querySelector(".row-actions").append(remove);target.append(el)})}catch(error){target.className="notice error";target.textContent=error.message}}
document.querySelector("#add-mail").onclick=()=>{document.querySelector("#mail-form").reset();document.querySelector("#mail-message").textContent="";mailDialog.showModal()};
document.querySelector("#mail-form").addEventListener("submit",async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));values.imapPort=Number(values.imapPort);values.smtpPort=Number(values.smtpPort);try{await api("/v1/management/mail/accounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});mailDialog.close();await loadMail()}catch(error){document.querySelector("#mail-message").textContent=error.message}});
async function loadCalendars(){const target=document.querySelector("#calendar-list");target.className="loading";target.textContent="Loading calendar connections…";try{const list=pick(await api("/v1/management/calendar/accounts"));target.className=list.length?"catalog":"empty";target.replaceChildren();if(!list.length){target.textContent="No calendars connected.";return}list.forEach(item=>{const el=row(item,{accent:"#ff6b9d",readOnly:true},{actions:false}),remove=document.createElement("button");remove.className="remove";remove.textContent="Remove calendar";remove.onclick=()=>{document.querySelector("#confirm-title").textContent=`Remove ${name(item)}?`;document.querySelector("#confirm-copy").textContent="This removes the connection and its synchronized events from this R1. It does not delete events from the calendar provider.";confirmJob=async()=>{await api(`/v1/management/calendar/accounts/${encodeURIComponent(id(item))}`,{method:"DELETE"});await loadCalendars();await loadConnections()};confirmDialog.showModal()};el.querySelector(".row-actions").append(remove);target.append(el)})}catch(error){target.className="notice error";target.textContent=error.message}}
document.querySelector("#add-calendar").onclick=()=>{document.querySelector("#calendar-form").reset();document.querySelector("#calendar-message").textContent="";showCalendarFields();calendarDialog.showModal()};
document.querySelector("#calendar-type").onchange=showCalendarFields;
function showCalendarFields(){const type=document.querySelector("#calendar-type").value;document.querySelector("#calendar-subscription-fields").hidden=type!=="ics_subscription";document.querySelector("#calendar-file-fields").hidden=type!=="ics_file";document.querySelector("#calendar-caldav-fields").hidden=type!=="caldav"}
document.querySelector("#calendar-form").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),values={type:String(data.get("type")),label:String(data.get("label")||"")};if(values.type==="ics_subscription")values.feedUrl=String(data.get("feedUrl")||"");if(values.type==="caldav"){values.calendarUrl=String(data.get("calendarUrl")||"");values.username=String(data.get("username")||"");values.password=String(data.get("password")||"")}if(values.type==="ics_file"){const file=data.get("icsFile");if(!(file instanceof File)||!file.size){document.querySelector("#calendar-message").textContent="Choose an ICS calendar file.";return}if(file.size>1500000){document.querySelector("#calendar-message").textContent="The ICS file must be 1.5 MB or smaller.";return}values.ics=await file.text()}try{await api("/v1/management/calendar/accounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});calendarDialog.close();await loadCalendars();await loadConnections()}catch(error){document.querySelector("#calendar-message").textContent=error.message}});
document.querySelectorAll("[data-close]").forEach(button=>button.onclick=()=>button.closest("dialog").close());function show(message){document.querySelector("#status-message").textContent=message}
})();
